spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

kafka:
  bootstrap:
    servers: localhost:9092
  topic:
    name: test
  consumer:
    group-id: group-id